version: "3.4"
services:
  vite_docker:
   image: node:alpine
   container_name: frontend_dev_container
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
      - .:/srv/app
      - /srv/app/node_modules
      #- ../server/src/model:/srv/server/src/model
   tty: true
   command: entrypoint.sh
   

volumes:
  node_modules:
   
