version: "3.4"
services:
  vite_docker:
   image: node:alpine
   container_name: frontend_dev_container
   entrypoint: /bin/sh
   ports:
     - 8000:8000
   working_dir: /srv/app
   volumes:
     - type: bind
       source: ./
       target: /srv/app
   tty: true
   command: entrypoint.sh
   
   
